# PERTEMUAN 2 MATRIKS

In [1]:
import numpy as np

In [3]:
#Skalar
scalar = np.array(5)
print("Skalar : ", scalar)
print("\n")

#Vektor Baris (1xn)
row_vector = np.array([1,2,3])
print("Vektor Baris : ", row_vector)
print("\n")

#Matriks 2D
matrix = np.array([[1,2,3],[4,5,6]])
print("Matriks 2D : ")
print(matrix)

#Matriks 3x3
m3x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matriks 3x3 : ")
print(m3x)

Skalar :  5


Vektor Baris :  [1 2 3]


Matriks 2D : 
[[1 2 3]
 [4 5 6]]
Matriks 3x3 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### OPERASI MATRIKS

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Penjumlahan
C = A + B
print("Hasil Penjumlahan : ")
print(C)

# Pengurangan
D = A - B
print("Hasil Pengurangan : ")
print(D)

# Perkalian
E = np.dot(np.dot(A, B), C)
print("Hasil Perkalian : ")
print(E)

# Transpose
A_T = A.T
print("Transpose A : ")
print(A_T)

Hasil Penjumlahan : 
[[ 6  8]
 [10 12]]
Hasil Pengurangan : 
[[-4 -4]
 [-4 -4]]
Hasil Perkalian : 
[[334 416]
 [758 944]]
Transpose A : 
[[1 3]
 [2 4]]


### OPERASI ELEMEN PADA MATRIKS

In [13]:
F = A * B
print("Perkalian Elemen-per-elemen : ")
print(F)

G = A ** 2
print("Pangkat Elemen : ")
print(G)

Perkalian Elemen-per-elemen : 
[[ 5 12]
 [21 32]]
Pangkat Elemen : 
[[ 1  4]
 [ 9 16]]


### PENYELESAIAN SPL dengan MATRIKS

In [16]:
# x + 2y = 10
# 3x + 4y = 24

A = np.array([[1,2],[3,4]])
B = np.array([10,24])

print("A")
print(A)
print("B")
print(B)

X = np.linalg.solve(A, B)
print("Solusi SPL : ", X)

A
[[1 2]
 [3 4]]
B
[10 24]
Solusi SPL :  [4. 3.]


### MANIPULASI MATRIKS

In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A)
print(B)

# Penggabungan Horizontal
H = np.hstack((A, B))
print("Hasil : ")
print(H)

# Penggabungan Vertikal
V = np.vstack((B, A))
print("Hasil : ")
print(V)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Hasil : 
[[1 2 5 6]
 [3 4 7 8]]
Hasil : 
[[5 6]
 [7 8]
 [1 2]
 [3 4]]
