# Pertemuan 8 - SPK dengan AHP

Studi Kasus: Pemilihan pembelian motor.

## Pengaturan Data

Penentuan **Alternatif** dan **Kriteria**
- Alternatif:
  - A1: Yamaha
  - A2: Honda
  - A3: Suzuki
  - A4: Kawasaki
- Kriteria:
  - C1: Gaya
  - C2: Keandalan
  - C3: Keekonomisan Bahan Bakar

**Tingkat Kepentingan**:
| Intensitas | Keterangan |
|------------|------------|
| 1 | X dan Y sama penting/baik |
| 2 | X sedikit lebih penting/baik dari Y |
| 3 | X lebih penting/baik dari Y |
| 4 | X jauh lebih penting/baik dari Y |

**Preferensi Kriteria**
1. *Keandalan* dua kali lebih penting dari gaya.
2. *Gaya* tiga kali lebih penting dari keekonomisan bahan bakar.
3. *Keandalan* empat kali lebih penting dari keekonomisan bahan bakar.

**Preferensi Alternatif**
1. Preferensi Gaya:
   - Kawasaki > Honda > Yamaha > Suzuki
2. Preferensi Keandalan:
   - Honda > Yamaha > Kawasaki > Suzuki 
3. Nilai Keekonomisan Bahan Bakar:
   - Yamaha  : 60
   - Honda   : 80
   - Suzuki  : 60
   - Kawasaki: 80

## Library dan Fungsi Normalisasi

**Library**

In [1]:
import numpy as np

**Fungsi Normalisasi**

In [3]:
def calc_norm(M):
    print('\nNormalisasi Matriks')
    if M.ndim == 1:  # Check if M is a vector
        sM = np.sum(M)
        return M / sM
    else:
        sM = np.sum(M, axis=0)
        return M / sM

## Step 1: Matrix Kriteria dan Eigenvector Kriteria

**Matrix**

In [2]:
# (G)   (A)    (E)    
MPBk = np.array([
    [1/1, 1/2, 3/1],  # (G-Gaya)
    [2/1, 1/1, 4/1],  # (A-Keandalan)
    [1/3, 1/4, 1/1]   # (E-Keekonomisan)
])
print(MPBk)

[[1.         0.5        3.        ]
 [2.         1.         4.        ]
 [0.33333333 0.25       1.        ]]


**Normalisasi**

In [4]:
# Normalisasi
w_MPB = calc_norm(MPBk)
print(w_MPB)


Normalisasi Matriks
[[0.3        0.28571429 0.375     ]
 [0.6        0.57142857 0.5       ]
 [0.1        0.14285714 0.125     ]]


**Eigenvector**

In [ ]:
m, n = w_MPB.shape
V = np.zeros(m)
for i in range(m):
    V[i] = np.sum(w_MPB[i, :])
    
print('Eigenvektor')
w_MPB = V / m
print(w_MPB)

## Step 2: Matrix Alternatif dan Eigenvector Alternatif

### Bandingkan Gaya

**Matrix**

In [14]:
print('\nPerbandingan Gaya: Alternatif Kualitatif Berpasangan')
AKB_G = np.array([
    [1/1, 1/2, 2/1, 1/3],
    [2/1, 1/1, 3/1, 1/2],
    [1/2, 1/3, 1/1, 1/4],
    [3/1, 2/1, 4/1, 1/1]
])
print(AKB_G)


Perbandingan Gaya: Alternatif Kualitatif Berpasangan
[[1.         0.5        2.         0.33333333]
 [2.         1.         3.         0.5       ]
 [0.5        0.33333333 1.         0.25      ]
 [3.         2.         4.         1.        ]]


**Normalisasi**

In [15]:
w_G = calc_norm(AKB_G)
print(w_G)


Normalisasi Matriks
[[0.15384615 0.13043478 0.2        0.16      ]
 [0.30769231 0.26086957 0.3        0.24      ]
 [0.07692308 0.08695652 0.1        0.12      ]
 [0.46153846 0.52173913 0.4        0.48      ]]


**Eigenvector**

In [16]:
m, n = w_G.shape
V = np.zeros(m)
for i in range(m):
    V[i] = np.sum(w_G[i, :])
    
print('Eigenvector')
w_G = V / m
print(w_G)

Eigenvector
[0.16107023 0.27714047 0.0959699  0.4658194 ]


### Bandingkan Keandalan

**Matrix**

In [17]:
print('Perbandingan Keandalan: Alternatif Kualitatif Berpasangan')
AKB_A = np.array([
    [1/1, 1/2, 3/1, 2/1],
    [2/1, 1/1, 4/1, 3/1],
    [1/3, 1/4, 1/1, 1/2],
    [1/2, 1/3, 2/1, 1/1]
])
print(AKB_A)

Perbandingan Keandalan: Alternatif Kualitatif Berpasangan
[[1.         0.5        3.         2.        ]
 [2.         1.         4.         3.        ]
 [0.33333333 0.25       1.         0.5       ]
 [0.5        0.33333333 2.         1.        ]]


**Normalisasi**

In [18]:
w_A = calc_norm(AKB_A)
print(w_A)


Normalisasi Matriks
[[0.26086957 0.24       0.3        0.30769231]
 [0.52173913 0.48       0.4        0.46153846]
 [0.08695652 0.12       0.1        0.07692308]
 [0.13043478 0.16       0.2        0.15384615]]


**Eigenvector**

In [19]:
m, n = w_A.shape
V = np.zeros(m)
for i in range(m):
    V[i] = np.sum(w_A[i, :])
    
print('Eigenvector')
w_A = V / m
print(w_A)

Eigenvector
[0.27714047 0.4658194  0.0959699  0.16107023]


### Bandingkan Keekonomisan Bahan Bakar

**Matrix**

In [20]:
print('Perbandingan Keekonomisan Bahan Bakar: Alternatif Kuantitatif')
ym = 60  # yamaha
hn = 80  # honda
sz = 60  # suzuki
kw = 80  # kawasaki
    
ACM_Fe = np.array([ym, hn, sz, kw])
print(ACM_Fe)

Perbandingan Keekonomisan Bahan Bakar: Alternatif Kuantitatif
[60 80 60 80]


**Normalisasi**

In [21]:
w_E = calc_norm(ACM_Fe)
print(w_E)


Normalisasi Matriks
[0.21428571 0.28571429 0.21428571 0.28571429]


## Step 3: Menghitung Vector Keputusan

**Gabung Nilai Eigenvector menjadi Matrix**

In [22]:
wM = np.column_stack((w_G, w_A, w_E))
print(wM)

[[0.16107023 0.27714047 0.21428571]
 [0.27714047 0.4658194  0.28571429]
 [0.0959699  0.0959699  0.21428571]
 [0.4658194  0.16107023 0.28571429]]


**Menghitung Score Akhir**

In [23]:
print('Nilai akhir untuk: yamaha, honda, suzuki, kawasaki')
MC_Scores = np.dot(wM, w_MPB)
print(MC_Scores)

Nilai akhir untuk: yamaha, honda, suzuki, kawasaki
[0.23226317 0.3833129  0.11047767 0.27394626]


**Mencari Motor Terbaik**

In [24]:
print('Nilai Motor terbaik terpilih berdasarkan manfaat (kriteria)')
Max_Motor_Score = np.max(MC_Scores)
print(Max_Motor_Score)

Nilai Motor terbaik terpilih berdasarkan manfaat (kriteria)
0.3833128995745455
